### ISSUE TITLE
OSError: dlopen failed: library "libc.so.6" not found

### ISSUE THREAD

**Issue by CrazyBoy2014** [sabamdarif/chroot-distro#98]
Happens when trying to download distro from docker hub.

**Comment by sabamdarif** [comment]
can you run chroot-distro info and send me what it shows

**Comment by CrazyBoy2014** [comment]
Never mind, I just needed to run as root.

**Comment by CrazyBoy2014** [comment]
I just got this when trying to login:

chroot_and_run: module 'os' has no attribute 'chroot'

Should I close this and open new issue?

**Comment by sabamdarif** [comment]
what version are you using ?

**Comment by sabamdarif** [comment]
> I just got this when trying to login:
> 
> chroot_and_run: module 'os' has no attribute 'chroot'
> 
> Should I close this and open new issue?

also update python the latest version

**Comment by sabamdarif** [comment]
and run apt info python and send me what it shows

**Comment by CrazyBoy2014** [comment]
Package: python
Version: 3.13.13-1
Maintainer: Yaksh Bariya <thunder-coding@termux.dev>
Installed-Size: 24.6 MB
Provides: python3
Depends: gdbm, libandroid-posix-semaphore,libbz2, libcrypt, libexpat, libffi, liblzma, libsqlite, ncurses, ncurses-ui-libs, openssl, readline, zlib
Recommends: python-ensurepip-wheels, python-pip
Breaks: python2 (<= 2.7.15), python-dev
Replaces: python-dev
Homepage: https://python.org/
Download-Size: 4521 kB
APT-Manual-Installed: no
APT-Sources: https://termux.net stable/main aarch64 Packages
Description: Python 3 programming language intended to enable clear programs

Here's chroot-distro info as well:

Chroot-Distro

  Program:           chroot-distro
  Version:           2.5.1
  Python:            3.13.13
  Executable:        /data/data/com.termux/files/usr/bin/chroot-distro
  Module path:       /data/data/com.termux/files/usr/lib/python3.13/site-packages
  Data location:     /data/data/com.termux/files/usr/var/lib/chroot-distro
  Cache location:    /data/data/com.termux/files/usr/var/lib/chroot-distro/cache
  OCI layer cache:   /data/data/com.termux/files/usr/var/lib/chroot-distro/cache/oci_layers

HOST

  Type:            Termux / Android
  Architecture:    aarch64 (supports 32-bit)
  Termux version:  unknown
  Termux package:  com.termux
  Android version: 16 (API 36)
  Device:          OnePlus CPH2719 (OP613BL1)
  Kernel:          16

HOST CAPABILITIES

  ✔ Privileges:      running as root
  ✔ /data mount:     rw,lazytime,seclabel,noatime,background_gc=on,nogc_merge,discard,discard_unit=block,user_xattr,inline_xattr,acl,inline_data,inline_dentry,noflush_merge,barrier,extent_cache,mode=adaptive,active_logs=6,reserve_root=134217,resuid=0,resgid=1065,inlinecrypt,alloc_mode=default,checkpoint_merge,fsync_mode=nobarrier,compress_algorithm=lz4,compress_log_size=2,compress_mode=user,memory=normal
  • Foreign arch:    binfmt_misc mounted, no qemu handler registered
  ✔ Namespaces:      unshare+nsenter present, user namespaces enabled
  • Disk (data dir): 169.4 GiB free of 221.2 GiB (76%)
  • Download cache:  5.8 KiB (clear with 'chroot-distro clear-cache')
  • OCI layer cache: 38.8 MiB (clear with 'chroot-distro clear-cache')

KERNEL CONFIG

  Read from /proc/config.gz

  Namespace isolation (--isolated, CD_USE_NS=1)
    ✔ CONFIG_NAMESPACES: enabled (namespace support (umbrella))
    ✘ CONFIG_PID_NS:     missing (required) (PID namespace (escape-proof /proc))
    ✔ CONFIG_UTS_NS:     enabled (UTS namespace (container hostname))
    ✘ CONFIG_IPC_NS:     missing (required) (IPC namespace)
    ⚠ CONFIG_USER_NS:    missing (optional) (user namespace (rootless extras))
    ✔ CONFIG_NET_NS:     enabled (network namespace (not yet used))

  Pseudo-filesystems (every chroot login)
    ✔ CONFIG_PROC_FS:     enabled (procfs (/proc))
    ✔ CONFIG_SYSFS:       enabled (sysfs (/sys))
    ✔ CONFIG_UNIX98_PTYS: enabled (devpts (/dev/pts login ptys))
    ⚠ CONFIG_DEVTMPFS:    missing (optional) (devtmpfs (/dev population))
    ✔ CONFIG_TMPFS:       enabled (tmpfs (fresh /dev, /dev/shm))

  Cgroups
    ✔ CONFIG_CGROUPS:       enabled (cgroup support (umbrella))
    ⚠ CONFIG_CGROUP_DEVICE: missing (optional) (device access control)
    ✔ CONFIG_MEMCG:         enabled (memory controller)
    ⚠ CONFIG_CGROUP_PIDS:   missing (optional) (pids controller)

  ✘ Namespace isolation (--isolated, CD_USE_NS=1) cannot work fully without: CONFIG_PID_NS, CONFIG_IPC_NS.

INSTALLED IMAGES

  1 container(s), 1.2 GiB total

  NAME       SIZE  ARCH     SOURCE            STATUS
  ubuntu  1.2 GiB  aarch64  ubuntu (aarch64)  idle

  Running now: 0 of 1 container(s)

ANALYSIS

  No issues detected across 1 container(s).

  Report issues at https://github.com/sabamdarif/chroot-distro/issues

**Comment by sabamdarif** [comment]
update to the latest version 3.14.6-1

**Comment by CrazyBoy2014** [comment]
But in termux it shows me that 3.13.13-1 is latest version?

python is already the newest version (3.13.13-1).
python set to manually installed.
Summary:
  Upgrading: 0, Installing: 0, Removing: 0, Not Upgrading: 0

Do I have to build python from source?

**Comment by sabamdarif** [comment]
run termux-change-repo and select the official termux repo , then upgrade python 
or download and install the latest build from here https://github.com/termux/termux-packages/actions/runs/28680714997?pr=30310

**Comment by kumardeo** [comment]
I was facing the same issue when trying to login (chroot-distro v2.5.0 and python v3.13):
> chroot_and_run: module 'os' has no attribute 'chroot'

After updating chroot-distro to v2.5.2 and python to v3.14, I am able to login.

**Comment by CrazyBoy2014** [comment]
Alright that fixed it, thanks
But I don't think it will be too hard to add a message saying "Run chroot-distro as root" when chroot-distro isn't run as root when doing commands such as chroot-distro login and chroot-distro install.

**Comment by sabamdarif** [comment]
but chroot-distro automatically run itself as root , and if you have no root access then it will just show the usual No su program found on this device message from termux's su

**Comment by sabamdarif** [comment]
but you are right i should add one anyway
